# Generated by Django 4.1.1 on 2022-10-18 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_mensajes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='avatar',
        ),
    ]
