# Generated by Django 4.1.1 on 2022-10-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_mensajes_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
