# Generated by Django 4.1.1 on 2022-10-19 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_comentario_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
