# Generated by Django 4.1.1 on 2022-09-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('autor', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('texto', models.TextField()),
            ],
        ),
    ]
