# Generated by Django 4.1.1 on 2022-09-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_entrada',
            field=models.IntegerField(default=0),
        ),
    ]
