# Generated by Django 4.1.1 on 2022-10-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_alter_pregunta_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
