# Generated by Django 4.1.1 on 2022-10-19 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='email',
        ),
    ]
