# Generated by Django 4.1.1 on 2022-10-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_remove_pregunta_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pregunta',
            field=models.TextField(null=True),
        ),
    ]
