# Generated by Django 4.1.1 on 2022-10-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_alter_pregunta_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pregunta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
